[package]
name = "cjdnstool"
version = "0.1.0"
authors = ["Ilyas Gasanov <torso.nafi@gmail.com>"]
edition = "2021"
description = "Command line tool for querying cjdns admin API."

[dependencies]
anyhow = "1.0"
cjdns-admin = { git = "https://github.com/cjdelisle/cjdns-route-server", rev = "0b2e8ae3d0b2c4d64095bdad8bc61c56455914bd", version = "0.1.0" }
clap = { version = "4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.27", features = ["fs", "net", "macros", "time", "rt-multi-thread", "sync"] }
