[workspace]
members = ["rust/cjdns_sys"]

[profile.release]
opt-level = 2
panic = "unwind"

# In debug mode, enable optimizations for dependencies, but not for our code
[profile.dev.package."*"]
opt-level = 2
